excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://johntravier969.github.io
title: Awesome Contents 2016
tagline: A log of everyday life
description: Please you to read more contents here 2016
paginate: 10